### PR TITLE
Added feature to create/update an index template

### PR DESCRIPTION
**Pull request by antoniocascais**
With this change you can now create/update an index template by setting
its name and its JSON body in the properties.

To create/update an index template, we just call the index API with a
PUT request. This is done in the `put-index-template.sh` script, which
is triggered by the `post-deploy` script.

Without this feature, users can now manage their index templates within
their bosh deployments.

### CODE REVIEW

**Comment by making** [comment]
Thanks for the contribution!

If this a one-time task, i'd use [bosh errand](https://bosh.io/docs/errands/).

I'd run like following after the deployment:

```
bosh -e elasticsearch run-errand put-index-template
```

curator-bosh-release could be referred as an example
https://github.com/bosh-elastic-stack/curator-boshrelease

**Comment by antoniocascais** [comment]
I wasn't aware of that concept.

Thanks for the suggestion @making, I changed it and made another commit :)

**Comment by antoniocascais** [comment]
Just pushed another commit to have the job accepting an array of index templates. Like this we can create several index templates at the same time.

**Comment by making** [comment]
LGTM
Thanks!

**Comment by making** [comment]
FYI: I've supported bosh link in the errand via https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/commit/69416d3a628ed0171125e338262ca2f292a3b7d9 so that errand can be run in a different vm

**Pull request merged**
